### ISSUE TITLE
Getting error in the POST request http://localhost:9090/screens/

### ISSUE THREAD

**Issue by gameboy-007** [gauravano/Ticket-Booking-Platform---Udaan-dev-challenge#1]
I followed the steps as per the Readme and got the db synced. But on running this POST request " http://localhost:9090/screens/" in postman and giving the same input in body as in the screenshot, I am getting back this error.

**Input given :** 

{ "name":"inox", "seatInfo": { "A": { "numberOfSeats": 10, "aisleSeats": [0, 5 ,6, 9] }, "B": { "numberOfSeats": 15, "aisleSeats": [0, 5 ,6, 9] }, "D": { "numberOfSeats": 20, "aisleSeats": [0, 5 ,6, 9] } } }

**Error:**

`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>TypeError: Cannot read property &#39;A&#39; of undefined
            <br> &nbsp; &nbsp;at C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\routes\api\**screens.js:7:40**
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\layer.js:95:5)
            <br> &nbsp; &nbsp;at next (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\route.js:137:13)
            <br> &nbsp; &nbsp;at Route.dispatch (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\route.js:112:3)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\layer.js:95:5)
            <br> &nbsp; &nbsp;at C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:281:22
            <br> &nbsp; &nbsp;at Function.process_params (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:335:12)
            <br> &nbsp; &nbsp;at next (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:275:10)
            <br> &nbsp; &nbsp;at Function.handle (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:174:3)
            <br> &nbsp; &nbsp;at router (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:47:12)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:317:13)
            <br> &nbsp; &nbsp;at C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:335:12)
            <br> &nbsp; &nbsp;at next (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:275:10)
            <br> &nbsp; &nbsp;at Function.handle (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:174:3)
            <br> &nbsp; &nbsp;at router (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:47:12)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:317:13)
            <br> &nbsp; &nbsp;at C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:335:12)
            <br> &nbsp; &nbsp;at next (C:\Users\Deepesh\Environments\Ticket-Booking-Platform---Udaan-dev-challenge\node_modules\express\lib\router\index.js:275:10)
        </pre>
    </body>
</html>`

It says  **"Cannot read property 'A' of undefined"**, though I can't figure out what is wrong in the code as I provided the correct input in the body in postman. Please help.

**Comment by gameboy-007** [comment]
Solved.
